// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYJ7pdHKljjodBEnB98T5QbeEfxxSrFNw',
    appId: '1:926242662602:web:39dfea46dc287cdd712c33',
    messagingSenderId: '926242662602',
    projectId: 'todoflutter-c25b7',
    authDomain: 'todoflutter-c25b7.firebaseapp.com',
    storageBucket: 'todoflutter-c25b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJ-zgPkYZUO2TFIDhQur1ESkjQ9GABts',
    appId: '1:926242662602:android:c7a52474b7484626712c33',
    messagingSenderId: '926242662602',
    projectId: 'todoflutter-c25b7',
    storageBucket: 'todoflutter-c25b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv7GIqje3dVI2b7SCuZ0zH66I3kjzUeGw',
    appId: '1:926242662602:ios:fb3aeafc79d21b1b712c33',
    messagingSenderId: '926242662602',
    projectId: 'todoflutter-c25b7',
    storageBucket: 'todoflutter-c25b7.appspot.com',
    iosClientId: '926242662602-l28c8742r0h2b3mp89munl0sl7kngqnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv7GIqje3dVI2b7SCuZ0zH66I3kjzUeGw',
    appId: '1:926242662602:ios:fb3aeafc79d21b1b712c33',
    messagingSenderId: '926242662602',
    projectId: 'todoflutter-c25b7',
    storageBucket: 'todoflutter-c25b7.appspot.com',
    iosClientId: '926242662602-l28c8742r0h2b3mp89munl0sl7kngqnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTodo',
  );
}
